### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by RyanSquared** [ChickenNuggers/Alchemy#4]
Comment with suggestions
- [X] Modules
  - [x] Access to `app` through module
    - [x] Async module data requests 
- [x] ~~Content generation class~~
- [X] Monitoring of...
  - [X] Memory
  - [X] CPU Usage...
    - [X] currently
    - [x] ~~over time~~
  - [X] Listening sockets
  - [X] Open sockets
